# Generated by Django 4.2.20 on 2026-02-10 19:28

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_ai_badges', '0002_badgeclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='course_id',
            field=opaque_keys.edx.django.models.CourseKeyField(blank=True, help_text='Course associated with this session', max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BadgeAssertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('recipient_hashed', models.BooleanField(default=True)),
                ('recipient_salt', models.CharField(max_length=64)),
                ('recipient_identity', models.CharField(max_length=255)),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='openedx_ai_badges.badgeclass')),
            ],
        ),
    ]
