# Generated by Django 4.2.20 on 2026-02-10 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openedx_ai_badges', '0003_badgeclass_course_id_badgeassertion'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeassertion',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with this session', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
